openapi: 3.0.0
info:
  description: >-
     Provider of Services to UAM (PSU) 
  version: "1.0.0-oas3"
  title: WX-data
  termsOfService: 'http://uam.arc.nasa.gov/terms'
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: shivanjli.sharma@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'
paths:
  /con-wx-operating-point-data-station:
    post:
      summary: Upload array of ConWxOperatingPointDataStation models.
      responses:
        '200':
          description: Data received. No content returned.
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/master/datacollection/openapi/v2/schema/uam-domain-commons-2.0.yaml#/definitions/UTMRestResponse
        '400':
          description: Bad request. Typically validation error. Fix your request and retry.
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/master/datacollection/openapi/v2/schema/uam-domain-commons-2.0.yaml#/definitions/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/master/datacollection/openapi/v2/schema/uam-domain-commons-2.0.yaml#/definitions/UTMRestResponse
        '403':
          description: >-
            Forbidden. Do not retry with same access token. Reason not provided,
            but do you have the right scopes? Does uss_name match the sub claim?
          content:
            application/json:
              schema:
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/master/datacollection/openapi/v2/schema/uam-domain-commons-2.0.yaml#/definitions/UTMRestResponse
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: >-
                  https://raw.githubusercontent.com/nasa/uam-apis/master/datacollection/openapi/v2/schema/schema-uam-wx-data-station-2.0.yaml#/definitions/ConWxOperatingPointDataStation
        description: Array of ConWxOperatingPointDataStation models
        required: true
servers:
  - url: 'https://utmregistry.arc.nasa.gov./api/v4'
