openapi: 3.0.0
info:
  version: "v1.0-oas3"
  title: ADS-B Out
  description: OpenAPI 2.0 compliant definitions for ADS-B Out data.
paths:
  /no-paths:
    put:
      responses:
        '410':
          description: >-
            Gone. Not implemented. Will not be implemented. Path included for
            proper use by automated tooling.
components:
  schemas:
      ADSBObject:
        type: object
        required:
          - aircraft
        properties:
          aircraft:
            type: array
            items:
              $ref: '#/components/schemas/ADSBModel'
      ADSBModel:
        type: object
        required:
          - icaoAddress
        properties:
          icaoAddress:
            type: string
            pattern: '^[0-9a-fA-F]{6}$'
            description: ICAO of the aircraft
          trafficSource:
            type: integer
            enum:
              - 0
              - 1
            description: '0 = 1090, 1 = UAT'
          latDD:
            type: number
            description: Latitude expressed as decimal degrees
          lonDD:
            type: number
            description: Longitude expressed as decimal degrees
          altitudeMM:
            type: number
            description: Geometric altitude or barometric pressure altitudein millimeters
          headingDE2:
            type: number
            description: Course over ground in centi-degrees
          horVelocityCMS:
            type: integer
            description: Horizontal velocity in centimeters/sec
          verVelocityCMS:
            type: integer
            description: Vertical velocity in centimeters/sec with positive being up
          squawk:
            type: number
            pattern: '^[0-7]{4}$'
            description: Squawk code
          altitudeType:
            type: integer
            enum:
              - 0
              - 1
            description: 'Altitude Source, 0 is pressure, 1 is geometric'
          callsign:
            type: string
            pattern: '^[A-Z0-9]+ *$'
          emitterType:
            type: integer
            enum: [0, 1, 2, 3, 4, 5]
            description: >-
              Category type of the emitter 0  = No aircraft type information 1  =
              Light (ICAO) < 15,500 lbs 2  = Small -15,500 to 75,000 lbs 3  =
              Large -75,000 to 300,000 lbs 4  = High Vortex Large (e.g., B757) 5
              = Heavy (ICAO) -> 300,000 lbs 6  = Highly Maneuverable > 5G
              acceleration and high speed 7  = Rotorcraft 8  = (Unassigned) 9  =
              Glider/sailplane 10 = Lighter than air 11 = Parachutist/sky diver 12
              = Ultralight/hang glider/paraglider 13 = (Unassigned) 14 = Unmanned
              aerial vehicle 15 = Space/trans-atmospheric vehicle 16 =
              (Unassigned) 17 = Surface vehicle-emergency vehicle 18 = Surface
              vehicle-service vehicle 19 = Point Obstacle (includes tethered
              balloons) 20 = Cluster Obstacle 21 = Line Obstacle 22-39 =
              (Reserved)
          utcSync:
            type: number
            description: UTC time flag
          timeStamp:
            $ref: '#/components/schemas/ADSBtimestamp'

      ADSBtimestamp:
        type: string
        format: date-time
        minLength: 22
        maxLength: 24
        example: '2015-08-20T14:11:56.118Z'
