openapi: 3.0.0
info:
  description: >-
    "UAM will require the submission of test data.  Some of these data are not
    readily collected via UTM means.  The models presented in this domain are in
    support of such data that are not readily collected otherwise.  Some of
    these data will be collected live, some after testing, but all should be
    collected as a soon as feasible.  Further details will be provided in other
    testing documentation."
  version: "1.0.0-oas3"
  title: Domain for UAM data collection models
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://uam.arc.nasa.gov/'
    email: shivanjli.sharma@nasa.gov
paths:
  /no-paths:
    put:
      responses:
        '410':
          description: >-
            Gone. Not implemented. Will not be implemented. Path included for
            proper use by automated tooling.  Tools sometimes do not like when
            there are no paths, but domains do not contain paths.
components:
  schemas:
    USSExchange:
      description: >-
        This model captures performance and interoperability data for a USS.
        since these data are not captured explicitly in the USS network, it is
        important to have USSs self report on these elements.  This information
        may inform future performance requirements and forensics of certain
        incidents. This may be an initial model that will be required
        operationally in terms of a USSs need to log interactions with other
        USSs.
      required:
        - metaDataDmpUss
        - measurement_id
        - event_id
        - exchanged_data_pk
        - exchanged_data_type
        - source_uss
        - target_uss
        - time_request_initiation
        - time_request_completed
        - actual_http_response
        - endpoint
        - http_method
      properties:
        metaDataDmpUss:
          $ref: >-
            https://raw.githubusercontent.com/nasa/utm-docs/master/TCL4%20Data%20Management/utm-tcl4-dmp-common.yaml#/definitions/metaDataDmpUss
        measurement_id:
          description: >-
            A UUID assigned by the reporting USS for this instance of
            USSExchange.
          type: string
          format: uuid
          maxLength: 36
          minLength: 36
          pattern: >-
            ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-4[0-9a-fA-F]{3}\-[8-b][0-9a-fA-F]{3}\-[0-9a-fA-F]{12}$
          example: 00000000-0000-4444-8888-FEEDDEADBEEF
        event_id:
          description: >-
            A string provided by the owner of the overall test (likely NASA)
            that identifies the event within which this data exchange occurs.
            NASA will define a pattern for this for consistency across tests.
          type: string
          minLength: 3
          maxLength: 100
          example: USS_SPRINT1_SIM_20180723_RUN5
        exchanged_data_pk:
          description: >-
            The primary key of the data that were exchanged.  For example, if an
            Operation was exchanged, then this field would contain the gufi.

            In the case that multiple data elements were exchanged (as in a GET
            to the Operations endpoint resulting in multiple Operations
            returned) then just populate this field with one of the primary
            keys. As a best practice, choose the first one in the array as they
            were sent between USSs.
          type: string
          format: uuid
          maxLength: 36
          minLength: 36
          pattern: >-
            ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-4[0-9a-fA-F]{3}\-[8-b][0-9a-fA-F]{3}\-[0-9a-fA-F]{12}$
          example: 00000000-0000-4444-8888-FEEDDEADBEEF
        exchanged_data_type:
          type: string
          enum:
            - OPERATION
            - POSITION
            - UTM_MESSAGE
            - CONSTRAINT_MESSAGE
            - NEGOTIATION_MESSAGE
            - USS_INSTANCE
            - DISCOVERY
            - OTHER_SEE_COMMENT
          example: POSITION
        source_uss:
          description: |-
            This is the uss_name of the source_uss.
            See MetaDataDmpUssId for definition of uss_name.
          type: string
          format: dns-name
          example: uss.provider123.net
        target_uss:
          description: |-
            This is the uss_name of the target_uss.
            See MetaDataDmpUssId for definition of uss_name.
          type: string
          format: dns-name
          example: utm.cool-uss-team.com
        reporting_uss_role:
          description: >-
            An enum indicating if the USS providing these data was the one that
            initiated the request (SOURCE_USS) or the USS that received the
            request (TARGET_USS).
          type: string
          enum:
            - SOURCE_USS
            - TARGET_USS
          example: SOURCE_USS
        time_request_initiation:
          description: >-
            If SOURCE_USS, this is the time that the request is sent to the
            TARGET_USS. If TARGET_USS, this is the time that the request was
            received from the SOURCE_USS.

            Same formatting rules as in other UTM exchanges (ms, 'Z').
          type: string
          format: date-time
          minLength: 24
          maxLength: 24
          pattern: >-
            ^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})Z$
          example: '2015-08-20T14:11:56.118Z'
        time_request_completed:
          description: >-
            If SOURCE_USS, this is the time that the response was received from
            the TARGET_USS. If TARGET_USS, this is the time that the request was
            sent back to the SOURCE_USS.

            Same formatting rules as in other UTM exchanges (ms, 'Z').
          type: string
          format: date-time
          minLength: 24
          maxLength: 24
          pattern: >-
            ^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})Z$
          example: '2015-08-20T14:11:56.118Z'
        endpoint:
          description: The endpoint to which the data request was initially sent.
          type: string
          format: url
          example: 'https://utm.cool-uss-team.com/operations'
        http_method:
          description: The HTTP method used in this exchange.
          type: string
          enum:
            - GET
            - POST
            - PUT
            - DELETE
            - HEAD
            - TRACE
            - OPTIONS
            - CONNECT
            - PATCH
          example: PUT
        expected_http_response:
          description: >-
            The expected HTTP response code. This is required ONLY if the
            reporting_uss_role is SOURCE_USS.
          type: integer
          format: int32
          minimum: 100
          exclusiveMinimum: false
          maximum: 599
          exclusiveMaximum: false
          example: 204
        actual_http_response:
          description: >-
            The actual HTTP response code sent by the TARGET_USS to the
            SOURCE_USS. Must be reported by USSs in either role.
          type: integer
          format: int32
          minimum: 100
          exclusiveMinimum: false
          maximum: 599
          exclusiveMaximum: false
          example: 204
        comments:
          description: >-
            Any additional comments that could aid in analysis involving these
            data.
          type: string
          maxLength: 1000
          example: This test was good.